name: ipython-notebook
channels:
  - conda-forge
dependencies:
  - notebook
  - keras
  - theano
  - scikit-learn
  - matplotlib
  - pip:
    - git+git://github.com/pl31/pgcontents.git
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
