name: ipython-notebook
dependencies:
  - notebook
  - ipywidgets
  - requests
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - keras:
    - git+git@github.com:fchollet/keras.git
  - matplotlib
  - sklearn:
    - git+git@github.com:scikit-learn/scikit-learn.git
  - theano:
    - git+git@github.com:Theano/Theano.git
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - git+git://github.com/pl31/pgcontents.git
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
